var ContentType = {
    /// <summary>
    /// 无指定类型，系统会将返回结果集直接response掉
    /// </summary>
    NONE:"NONE",
    /// <summary>
    /// Json
    /// </summary>
    Json: "Json",
    /// <summary>
    /// Html
    /// </summary>
    HTML: "HTML",
    /// <summary>
    /// 字符串
    /// </summary>
    String: "String",
    /// <summary>
    /// Jpg图片
    /// </summary>
    Pic_Jpg: "Pic_Jpg",
    /// <summary>
    /// Bmp图片
    /// </summary>
    Pic_Bmp: "Pic_Bmp",
    /// <summary>
    /// Gif图片
    /// </summary>
    Pic_Gif: "Pic_Gif",
    /// <summary>
    /// png图片
    /// </summary>
    Pic_png: "Pic_png",
    /// <summary>
    /// Excel
    /// </summary>
    Excel: "Excel",
    /// <summary>
    /// Word
    /// </summary>
    Word: "Word",
    /// <summary>
    /// PDF
    /// </summary>
    PDF: "PDF",
    /// <summary>
    /// HostView
    /// </summary>
    HostView: "HostView"
}